const fs = require('fs');
const path = require('path');
const chalk = require('chalk');

/**
 * Save article as Markdown with visible metadata in Read Mode
 */
function saveToMarkdown(article) {
    // 1. Setup output directory
    const outputDir = path.join(__dirname, '../../output');
    if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, { recursive: true });
    }

    // 2. Filename cleaning
    const safeFileName = article.title
        .replace(/[\\/:\*\?"<>|]/g, '')
        .substring(0, 60) + '.md';
    const filePath = path.join(outputDir, safeFileName);

    const escapeYaml = (str) => str ? str.replace(/"/g, '\\"') : '';

    // 3. YAML Frontmatter (For System/Database use)
    const frontmatter = [
        '---',
        `title: "${escapeYaml(article.title)}"`,
        `date: "${article.date}"`,
        `author: "${escapeYaml(article.author)}"`,
        `image: "${article.image}"`,
        `url: "${article.fullUrl}"`,
        'tags:',
        ...(article.keywords || []).map(tag => `  - "${tag}"`),
        '---'
    ].join('\n');

    // We use standard Markdown like bolding and bullet points
    // 4. Visible Metadata Block (One item per line)
    const visibleMetadata = [
        `**Date:** ${article.date}`,
        `**Author:** ${article.author}`,
        `**Source:** [Original Article](${article.fullUrl})`,
        `**Tags:** ${(article.keywords || []).map(tag => `#${tag.replace(/\s+/g, '')}`).join(' ')}`
    ].join('\n\n');

    // 5. Build Final Template
    const markdownTemplate = `${frontmatter}

# ${article.title}

${visibleMetadata}

---

![Cover Image](${article.image})

> **Summary**: ${article.summary}

---

${article.content}

---
*Generated by [Daily Knowledge Feeder] | 📅 Scraped at: ${new Date().toLocaleString()}*
`;

    // 6. Execution
    try {
        fs.writeFileSync(filePath, markdownTemplate.trim(), 'utf8');
        console.log(chalk.bold.green(`✅ File Saved: ${safeFileName}`));
    } catch (error) {
        console.error(chalk.red(`❌ Write Error: ${error.message}`));
    }
}

module.exports = { saveToMarkdown };