const fs = require('fs');
const path = require('path');
const chalk = require('chalk');

/**
 * Save article as Markdown with YAML Frontmatter
 */
function saveToMarkdown(article) {
    // 1. Setup output directory (root/output)
    const outputDir = path.join(__dirname, '../../output');
    if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, { recursive: true });
    }

    // 2. Generate safe filename (remove illegal characters)
    const safeFileName = article.title
        .replace(/[\\/:\*\?"<>|]/g, '')
        .substring(0, 60) + '.md';
    const filePath = path.join(outputDir, safeFileName);

    // 3. Helper: Escape double quotes for safe YAML strings
    const escapeYaml = (str) => str ? str.replace(/"/g, '\\"') : '';

    // 4. Build YAML Frontmatter (for Obsidian/Notion metadata)
    const frontmatter = [
        '---',
        `title: "${escapeYaml(article.title)}"`,
        `date: "${article.date}"`,
        `category: "${article.category}"`,
        `author: "${escapeYaml(article.author)}"`,
        `image: "${article.image}"`,
        `url: "${article.fullUrl}"`,
        'tags:',
        ...(article.keywords || []).map(tag => `  - "${tag}"`),
        '---',
        ''
    ].join('\n');

    // 5. Combine everything into one Markdown template
    const markdownTemplate = `
${frontmatter}
# ${article.title}

![Cover Image](${article.image})

> **💡 Summary**: ${article.summary}

---

${article.content}

---
*Generated by [Daily Knowledge Feeder] | 📅 Scraped at: ${new Date().toLocaleString()}*
`;

    // 6. Write file to disk
    try {
        fs.writeFileSync(filePath, markdownTemplate.trim(), 'utf8');
        console.log(chalk.bold.green(`✅ Success: ${safeFileName}`));
    } catch (error) {
        console.error(chalk.red(`❌ Write Error: ${error.message}`));
    }
}

module.exports = { saveToMarkdown };